### ISSUE TITLE
Release to maven central

### ISSUE THREAD

**Issue by lbehnke** [dspinellis/UMLGraph#21]
I'd love to see a recent version of UMLGraph in maven central, for UMLGraph 5.1 is not compatible with Java 7.

**Comment by ahonorat** [comment]
Hi, I can see the version 5.7.2 on maven-repository website but the download fails. Actually it appears that the directory for version 5.7.2 is missing since there is 404 error on the expected [url](https://oss.sonatype.org/content/repositories/staging/org/umlgraph/umlgraph/5.7.2/), see also the [root directory](https://oss.sonatype.org/content/repositories/staging/org/umlgraph/umlgraph/).
Thanks anyway, useful tool :)

**Comment by dspinellis** [comment]
See also #46.
